### ISSUE TITLE
Patching unsquashfs.c failing

### ISSUE THREAD

**Issue by raverrr** [devttys0/sasquatch#11]
Getting this error when trying to build:

patching file squashfs-tools/unsquashfs.c
cc -g -O2  -I. -I./LZMA/lzma465/C -I./LZMA/lzmalt -I./LZMA/lzmadaptive/C/7zip/Compress/LZMA_Lib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DCOMP_DEFAULT=\"gzip\" -Wall -Werror  -DGZIP_SUPPORT -DLZMA_SUPPORT -DXZ_SUPPORT -DLZO_SUPPORT -DXATTR_SUPPORT -DXATTR_DEFAULT   -c -o unsquashfs.o unsquashfs.c
unsquashfs.c: In function ‘read_super’:
unsquashfs.c:1988:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if(!comp)
     ^~
unsquashfs.c:1990:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
  return TRUE;
  ^~~~~~
cc1: all warnings being treated as errors
<builtin>: recipe for target 'unsquashfs.o' failed
make: *** [unsquashfs.o] Error 1

**Comment by raverrr** [comment]
Ok I looked myself and it's this:

@@ -1893,6 +1984,8 @@
 	/*
 	 * 1.x, 2.x and 3.x filesystems use gzip compression.
 	 */
+    // CJH: Check to see if comp has alredy been defined
+    if(!comp)
 	comp = lookup_compressor("gzip");
 	return TRUE;

Seeing as it was just a check i deleted it and it compiled fine. However I have absolutely no idea how important it was lol

**Comment by devttys0** [comment]
I made an update to the patch in the latest master branch which should fix this. Thanks!
