### ISSUE TITLE
FNM_EXTMATCH error

### ISSUE THREAD

**Issue by acoul** [devttys0/sasquatch#15]
on a void-linux-64, a musl-libc system:

`unsquashfs.c: In function 'matches':
unsquashfs.c:1442:35: error: 'FNM_EXTMATCH' undeclared (first use in this function)
     name, FNM_PATHNAME|FNM_PERIOD|FNM_EXTMATCH) ==`

maybe this will [help](http://lists.busybox.net/pipermail/buildroot/2016-February/151459.html)

**Comment by devttys0** [comment]
Please report upstream to SquashFS.

**Comment by E3V3A** [comment]
I guess you could include the patch?
