### ISSUE TITLE
Bashism in build.sh

### ISSUE THREAD

**Issue by voltagex** [devttys0/sasquatch#8]
The UID check appears to be a bashism, as it doesn't run under sh

e.g.

```
$ if [ "$UID" == "0" ]
then
    SUDO=""
else
    SUDO="sudo"
fi> > > > >
sh: 6: [: unexpected operator
```
(actually, the problem is with the ==, which only works in double brackets)

**Comment by devttys0** [comment]
Fixed, thanks!
